In [1]:
import os
import matplotlib.pyplot as plt
import joblib
import numpy as np

plt.style.use("fivethirtyeight")

In [3]:
class perceptron:
    def __init__(self,eta: float = None, epochs: int = None):
        self.weights = np.random.randn(3) * 1e-4
        self.eta = eta
        self.epochs = epochs
        
        
    def fit(self, X, y):
        self.X = X
        self.y = y
        
        X_with_bias = np.c_[self.X, -np.ones((len(self.X),1))]
        print(f"X with bias: \n{X_with_bias}")
        
        

In [6]:
obj = perceptron(eta = 0.01, epochs = 10)

In [7]:
obj.eta

0.01

In [11]:
X = np.ones((4,2))
X

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [12]:
y = np.ones((4,1))
y

array([[1.],
       [1.],
       [1.],
       [1.]])

In [14]:
obj.fit(X,y)

X with bias: 
[[ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]]
