In [60]:
import os
import matplotlib.pyplot as plt
import joblib
import numpy as np
import pandas as pd

plt.style.use("fivethirtyeight")

In [61]:
class perceptron:
    def __init__(self,eta: float = None, epochs: int = None):
        self.weights = np.random.randn(3) * 1e-4
        self.eta = eta
        self.epochs = epochs
        
        
    def _z_outcome(self, inputs, weights):
        return np.dot(inputs,weights)
    
    
    def activation_function(self, z):
        return np.where(z > 0,1,0)
    
    
    def fit(self, X, y):
        self.X = X
        self.y = y
        
        X_with_bias = np.c_[self.X, -np.ones((len(self.X),1))]
        print(f"X with bias: \n{X_with_bias}")
        
        for epochs in range(self.epochs):
            print("--"*10)
            print(f"for epoch >>{epochs+1}")
            print("--"*10)
            
            z = self._z_outcome(X_with_bias, self.weights)
            y_hat = self.activation_function(z)
            print(f"predicted value after forward pass: \n{y_hat}")
            
            self.error = self.y - y_hat
            print(f"error: \n{self.error}")
            
            self.weights = self.weights + self.eta * np.dot(X_with_bias.T, self.error)
            print(f"updated weights after epochs:{epochs+1}/{self.epochs} : \n{self.weights}")
            print(f"##"*10)
    
    
    def predict(self, X):
        X_with_bias = np.c_[X, -np.ones((len(X),1))]
        z = self._z_outcome(X_with_bias,self.weights)   
        return self.activation_function(z)
    
    
    
    

In [62]:
OR = {
    "x1" : [0,0,1,1],
    "x2" : [0,1,0,1],
    "y" : [0,1,1,1]
}

In [63]:
df = pd.DataFrame(OR)
df

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [64]:
def prepare_data(df, target_col = "y"):
    X = df.drop(target_col, axis = 1)
    y = df[target_col]
    
    return (X,y)
    

In [65]:
X, y = prepare_data(df)
ETA = 0.1
EPOCHS = 10
model_or = perceptron(eta = ETA, epochs= EPOCHS)

model_or.fit(X,y)

X with bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch >>1
--------------------
predicted value after forward pass: 
[1 0 0 0]
error: 
0   -1
1    1
2    1
3    1
Name: y, dtype: int64
updated weights after epochs:1/10 : 
[ 0.19983267  0.19986267 -0.20000404]
####################
--------------------
for epoch >>2
--------------------
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epochs:2/10 : 
[ 0.19983267  0.19986267 -0.10000404]
####################
--------------------
for epoch >>3
--------------------
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epochs:3/10 : 
[ 1.99832670e-01  1.99862666e-01 -4.03872934e-06]
####################
--------------------
for epoch >>4
--------------------
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Nam

In [66]:
X

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [67]:
y

0    0
1    1
2    1
3    1
Name: y, dtype: int64

In [68]:
model_or.predict(X)

array([0, 1, 1, 1])

In [69]:
XOR = {
    "x1" : [0,0,1,1],
    "x2" : [0,1,0,1],
    "y" : [0,1,1,0]
} 

In [70]:
df_XOR = pd.DataFrame(XOR)
df_XOR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  0

In [71]:
X, y = prepare_data(df_XOR)

In [76]:
model_xor = perceptron(eta= ETA, epochs= EPOCHS)
model_xor.fit(X,y)


X with bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch >>1
--------------------
predicted value after forward pass: 
[0 0 0 0]
error: 
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights after epochs:1/10 : 
[ 0.09999035  0.09993701 -0.19986375]
####################
--------------------
for epoch >>2
--------------------
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights after epochs:2/10 : 
[-9.64724234e-06 -6.29921528e-05  1.36250431e-04]
####################
--------------------
for epoch >>3
--------------------
predicted value after forward pass: 
[0 0 0 0]
error: 
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights after epochs:3/10 : 
[ 0.09999035  0.09993701 -0.19986375]
####################
--------------------
for epoch >>4
--------------------
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3   -1
Nam

In [77]:
model_xor.predict(X)

array([0, 0, 0, 0])

In [78]:
#XOR is non-linearly seperable that's why it is not giving correct value